About Us work done
HackSlashNITP/ByteVerse_Website pull request #3
Opened 2024-01-24 12:34 UTC by dev04sa

@Abhinav1341  About us part Work done. I implement all necessary components and animations. also I added the social links of Instagram an linkedin review the changes .

![Screenshot 2024-01-24 180019](https://github.com/HackSlashNITP/ByteVerse_Website/assets/129666293/64b948b2-7a3c-4942-9334-3a69a896d11c)

video link : 
[b4d4273e-3540-4714-b547-fc5686bf8ad2.webm](https://github.com/HackSlashNITP/ByteVerse_Website/assets/129666293/3e716029-cc42-4d16-9973-395fc8498575)

2024-01-24 13:41 UTC, RitwikSingh28 commented on byteverse_24/src/app/components/AboutIamge.jsx
> +        className="dark:invert  "
@dev04sa 
I don't think we would want to invert the colors when a user is in dark mode. For that will alter the color scheme completely. Do remember that most of the users use their phones in dark mode itself.

2024-01-24 13:42 UTC, RitwikSingh28 commented on byteverse_24/src/app/components/HeadImage.jsx
> +              className="dark:invert"
Same here. Please remove the class `dark:invert`

2024-01-24 13:43 UTC, RitwikSingh28 commented on byteverse_24/src/app/components/KnifeImage.jsx
> +    console.log("Animation 1 complete. Current state:", animationState1);
@dev04sa 
Always remember, when pushing your code onto production branch, you must remove any logs to the console.

2024-01-24 13:45 UTC, RitwikSingh28 requested changes
@dev04sa 
Please look into the comments I have provided, and try to address them by pushing subsequent commits to this PR.

Moreover, there is a glitch I came across. When in mobile view, the `ninja-icon` covers the GDSC Logo. Please try to get that fixed.

2024-01-24 14:08 UTC, dev04sa commented
@RitwikSingh28  Sir I have done all the changes as u told please review the changes.
[3af7913c-9302-40c6-904e-a40add0d443f.webm](https://github.com/HackSlashNITP/ByteVerse_Website/assets/129666293/b28d646d-650f-4c9d-bb9a-bd4ecf1cb3d8)

2024-01-24 14:27 UTC, RitwikSingh28 commented
@dev04sa 
The glitch is still there, if you diminish the viewport further. 
Moreover, in the video you have provided, you may also notice that the social media logos for HackSlash vanish in the mobile view.

2024-01-24 17:48 UTC, dev04sa commented
@RitwikSingh28  Sir issue resolved

![Screenshot 2024-01-24 230703](https://github.com/HackSlashNITP/ByteVerse_Website/assets/129666293/eb3addae-6cbf-4d81-8562-846565ae0834)
[551bb768-b06c-4656-9854-4ea38607bcbc.webm](https://github.com/HackSlashNITP/ByteVerse_Website/assets/129666293/170425b6-9ecd-45b3-b40e-216302c344f7)

2024-01-25 02:21 UTC, RitwikSingh28 commented
@dev04sa 
Great work! All the issues have been addressed...

2024-01-25 02:22 UTC, merged